# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions += ['sphinxcontrib.seqdiag']
 
# The encoding of source files.
source_encoding = 'utf-8-sig'
#source_encoding = 'shift_jis'
 
# The language for content autogenerated by Sphinx.
#language = 'en'

# The theme to use for HTML and HTML Help pages.
#html_theme = 'default'
#html_theme = 'sphinxdoc'
#html_theme = 'scrolls'
#html_theme = 'agogo'
#html_theme = 'traditional'
#html_theme = 'nature'
#html_theme = 'haiku'
 
